# Generated by Django 4.0.1 on 2022-06-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_eventpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('seen', models.BooleanField(default=False)),
                ('date_sent', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
