# Generated by Django 4.0.1 on 2022-07-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
