# Generated by Django 4.0.1 on 2022-07-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_comment_likes_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpayment',
            name='event_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
