# Generated by Django 4.0.1 on 2022-06-07 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('artist', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to=mainapp.models.uploaded_path)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=mainapp.models.uploaded_path)),
                ('genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.genre')),
            ],
        ),
    ]
