# Generated by Django 4.0.1 on 2022-06-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_artist_album_logo_alter_album_album_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='album_logo',
            new_name='photo',
        ),
    ]
