# Generated by Django 4.0.1 on 2022-06-11 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_rename_album_logo_artist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='date_joined',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='artistsong',
            name='album_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.album'),
        ),
        migrations.AlterField(
            model_name='artistsong',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.artist'),
        ),
        migrations.AlterField(
            model_name='artistsong',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='media/artist_songs/'),
        ),
        migrations.AlterField(
            model_name='artistsong',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.genre'),
        ),
        migrations.AlterField(
            model_name='artistsong',
            name='song_logo',
            field=models.ImageField(blank=True, default='media/default.PNG', null=True, upload_to='media/Song_logo/'),
        ),
    ]
