# Generated by Django 4.0.1 on 2022-06-14 18:36

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_artist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='descriptions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=mainapp.models.uploaded_path),
        ),
    ]
