# Generated by Django 4.0.1 on 2022-06-14 18:24

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_event_approved_event_descriptions_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('artist', models.CharField(max_length=30)),
                ('song_logo', models.ImageField(blank=True, null=True, upload_to=mainapp.models.uploaded_path)),
                ('audio_file', models.FileField(upload_to='media/songs')),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.genre')),
            ],
        ),
    ]
