# Generated by Django 4.0.1 on 2022-06-17 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_event_tickets_event_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.FloatField(blank=True, null=True, verbose_name='General')),
                ('regular', models.FloatField(blank=True, null=True, verbose_name='Regular')),
                ('vip', models.FloatField(blank=True, null=True, verbose_name='VIP')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.ticket'),
        ),
    ]
