# Generated by Django 4.0.1 on 2022-06-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_ticket_event_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='general',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='regular',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='vip',
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
