# Generated by Django 4.0.1 on 2022-06-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_rename_general_ticket_cost_remove_ticket_regular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket',
        ),
        migrations.AddField(
            model_name='event',
            name='ticket',
            field=models.ManyToManyField(null=True, to='mainapp.Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Cost'),
        ),
    ]
