# Generated by Django 4.0.1 on 2022-06-17 12:20

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_remove_event_ticket_event_ticket_alter_ticket_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='general',
            field=models.FloatField(blank=True, null=True, verbose_name='General'),
        ),
        migrations.AddField(
            model_name='event',
            name='regular',
            field=models.FloatField(blank=True, null=True, verbose_name='Regular'),
        ),
        migrations.AddField(
            model_name='event',
            name='vip',
            field=models.FloatField(blank=True, null=True, verbose_name='VIP'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket',
        ),
        migrations.AddField(
            model_name='event',
            name='ticket',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=mainapp.models.uploaded_path),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
