# Generated by Django 4.0.1 on 2022-06-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_remove_event_image_event_general_event_regular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ticket',
            new_name='photo',
        ),
    ]
