# Generated by Django 4.0.1 on 2022-06-21 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0023_rename_ticket_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='account',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
