# Generated by Django 4.0.1 on 2022-06-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_artistsong_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='followers',
        ),
        migrations.AlterField(
            model_name='album',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Monetization cost,0 if Free'),
        ),
    ]
